language: c
notifications:
  email:
    recipients:
      - wbx@openadk.org
    on_success: always
    on_failure: always
git:
  depth: 3
matrix:
  include:
  - env: ARCH=arm SYSTEM=beaglebone-black
  - env: ARCH=arm SYSTEM=linksys-nslu2
  - env: ARCH=avr32 SYSTEM=atmel-ngw100
  - env: ARCH=avr32 SYSTEM=grasshopper
  - env: ARCH=cris SYSTEM=foxboard-lx832
  - env: ARCH=m68k SYSTEM=aranym-m68k
  - env: ARCH=mips SYSTEM=imgtec-ci20
  - env: ARCH=mips SYSTEM=mikrotik-rb4xx ENDIAN=big
  - env: ARCH=mips SYSTEM=mikrotik-rb532
  - env: ARCH=mips64 SYSTEM=lemote-yeelong
  - env: ARCH=nds32 SYSTEM=andes-ag101p
  - env: ARCH=sh SYSTEM=numato-mimasv2
  - env: ARCH=x86 SYSTEM=ibm-x40
  - env: ARCH=x86 SYSTEM=pcengines-alix
  - env: ARCH=x86_64 SYSTEM=pcengines-apu
  - env: ARCH=x86_64 SYSTEM=asus-p5bvm
  - env: ARCH=xtensa SYSTEM=xilinx-kintex7
script: travis_wait 120 ./scripts/travis.sh $ARCH $SYSTEM $ENDIAN
